version: '3.4'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    networks: 
      - backend-network
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
  
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8080:80
    networks:
      - frontend-network 
      - backend-network
    environment: 
      - PMA_ARBITRARY=1
    depends_on: 
      - mysql
    restart: always
  
  apache:
    build: ./apache
    ports: 
      - 80:80
    networks:
      - frontend-network 
      - backend-network
    depends_on: 
      - mysql
    restart: always

volumes:
  mysql_data:
  wordpress_data:

networks: 
  frontend-network:
  backend-network: